### ISSUE TITLE
Add date/time of reported stock to output embeds

### ISSUE THREAD

**Issue by DudeInCorner** [PilotsTradeNetwork/EDStockTraderProject#10]
Should be fairly simple, EDSM's market API doesn't return data date, but with some research we can likely find a way to get the last updated time of the data using EDSM's other APIs

**Comment by durzo** [comment]
https://github.com/PilotsTradeNetwork/EDStockTraderProject/pull/19

**Comment by DudeInCorner** [comment]
Closed with PR #19
