### ISSUE TITLE
Mobile friendly stock embed

### ISSUE THREAD

**Issue by gcruicks** [PilotsTradeNetwork/EDStockTraderProject#14]
The current embed for `;stock` is not mobile friendly due to how discord displays fields. The current responses on mobile do not give you any reasonable information about what the values pertain too

![image](https://user-images.githubusercontent.com/53232597/132575591-e8a53b48-2f7a-4521-9712-d90f265010fb.png)

It would be great if we could refactor this somehow into a view that works for both mobile and native clients

**Comment by durzo** [comment]
any ideas how to better format it?

**Comment by gcruicks** [comment]
My only thought is not to use the embed fields and values, but instead each line a string in the field name. But even then it’s not going to be universally cleN

**Comment by durzo** [comment]
How does this look?

Mobile:
![Screenshot_20210909-192335](https://user-images.githubusercontent.com/346775/132733705-2d15218f-68ab-42f7-8985-19dccd418fd5.jpg)


Desktop:
![Screenshot from 2021-09-09 19-24-21](https://user-images.githubusercontent.com/346775/132733672-2fb78b3c-8512-420c-899e-98467601f720.png)
