### ISSUE TITLE
Adding carriers via code only

### ISSUE THREAD

**Issue by DudeInCorner** [PilotsTradeNetwork/EDStockTraderProject#16]
In order to easily rebuild the carrier list (and simplify the adding process), we should implement a way to add carriers using just their codes.

Current suggestion is to use the Inara API to find the carrier's system, and then using the code + system and the EDSM API to add the carrier marketID.

**Comment by durzo** [comment]
pull #17 fixes this

**Comment by DudeInCorner** [comment]
Closed with PR #17
