### ISSUE TITLE
Carrier list and tracked carriers reverts to a list of 45 carriers upon bot restart

### ISSUE THREAD

**Issue by mvcircelli** [PilotsTradeNetwork/EDStockTraderProject#22]
The bot is reverting to the same list of 45 carriers upon every restart. I noticed this while restarting the bot to apply the latest PR, though I don't think the new update is responsible, since Admins were reporting something similar at the last update.

The missing carriers are **still in the local .carriers file, and the .carriers file in the repo has them as well** (it includes the PTN garden and PTN bragur, which were very recently added, and proved to be working, though upon bot restart they no longer appear in ;list and cannot be tracked via ;stock)

There were no error messages when adding the carriers either, I checked back to the last 5 added carriers and the logs all show the "carrier saved" printout each time a new carrier was added.

For good measure, I've already tried changing the .carriers file permissions to readable and writeable by all using chmod, though that does not appear to have changed anything.

**Comment by durzo** [comment]
Looks like the FLEET_CARRIERS variable is being taken from the .env file over the .carriers file.

please remove all carriers from .env file. this file should only contain DISCORD_TOKEN and DISCORD_GUILD variables.

the .carriers file should have the FLEET_CARRIERS variable

**Comment by mvcircelli** [comment]
Solved by removing the FLEET_CARRIERS variable from .env, and also had to delete the local .carriers file and replace it with the github copy, since the local's contents had been overwritten to only contain 45 carriers.
