### ISSUE TITLE
Add paging to active carrier list

### ISSUE THREAD

**Issue by DudeInCorner** [PilotsTradeNetwork/EDStockTraderProject#3]
The list of tracked carriers is getting quite long, it is only a matter of time before we exceed the allowed number of characters. Thus, it's time to add some paging functionality to the list, similar to how MisisonAlertBot's list functions.

**Comment by durzo** [comment]
This has been fixed and can be closed

**Comment by DudeInCorner** [comment]
Closed with PR #15
