### ISSUE TITLE
Improve first time setup and run experience

### ISSUE THREAD

**Issue by durzo** [PilotsTradeNetwork/EDStockTraderProject#4]
I ran into some trouble setting this up in my dev because there was no documentation or format checks around the .env file

1. With the way FC's are added, the code fails if there aren't enough lines in the .env and gives no explanation.
2. Documentation does not mention required variables in .env file.
3. Documentation does not mention required bot permissions on the discord application side - I still don't know what these are and therefore can't add them to the docs myself.

I have fixed 1-2 in my local dev. I'll make a merge request to fix these soon.

**Comment by DudeInCorner** [comment]
Closed with PR #5 and PR #6
