### ISSUE TITLE
Save active carriers in a .txt or other external file rather than in the .env

### ISSUE THREAD

**Issue by DudeInCorner** [PilotsTradeNetwork/EDStockTraderProject#7]
Saving the carriers in the .env proves rather problematic since we are unable to upload the .env to github, so having the carrier list be its own file that we can safely upload to github would make things much simpler, and provide a backup option so that we don't have to rebuild the list from scratch (again ;-;)

**Comment by durzo** [comment]
This issue can be closed now

**Comment by DudeInCorner** [comment]
PR #13 implements this
