### ISSUE TITLE
Consider signing up for Inara API as a substitute for cAPI

### ISSUE THREAD

**Issue by DudeInCorner** [PilotsTradeNetwork/EDStockTraderProject#9]
Inara's API tracks fleet carrier cargo using cAPI, and exposes it to its API, meaning that we could theoretically obtain a carrier's cargo with the same or similar reliability to directly using cAPI. Fleet Carrier Owners could pass their API keys to the bot as an extra field to the current enrolment system.

Downsides to this are that we need to sign up for the Inara API program, and the Inara API is significantly more complex to use.

Similarly, EDSM seems to have an API endpoint for commander cargo, though I suspect this is not as good of a substitute since it might include all cargo across all ships, as opposed to just FC cargo.

**Comment by durzo** [comment]
closing this as we have cAPI and Inara API does not return carrier cargo
